// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Api.Migrations
{
    [DbContext(typeof(GeneratorDbContext))]
    [Migration("20190623230424_allModels")]
    partial class allModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062");

            modelBuilder.Entity("Core.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Subject");

                    b.Property<string>("Teacher");

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.ToTable("Exams");
                });

            modelBuilder.Entity("Core.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answer");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Options");

                    b.Property<int>("QuestionTypeId");

                    b.Property<int>("SectionId");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("QuestionTypeId");

                    b.HasIndex("SectionId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("Core.Models.QuestionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.ToTable("QuestionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2019, 6, 23, 19, 4, 24, 4, DateTimeKind.Local).AddTicks(5670),
                            Type = "Verdadero o Falso",
                            Updated = new DateTime(2019, 6, 23, 19, 4, 24, 13, DateTimeKind.Local).AddTicks(6280)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2019, 6, 23, 19, 4, 24, 13, DateTimeKind.Local).AddTicks(7800),
                            Type = "Seleccion Multiple",
                            Updated = new DateTime(2019, 6, 23, 19, 4, 24, 13, DateTimeKind.Local).AddTicks(7800)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2019, 6, 23, 19, 4, 24, 13, DateTimeKind.Local).AddTicks(7810),
                            Type = "Seleccion Simple",
                            Updated = new DateTime(2019, 6, 23, 19, 4, 24, 13, DateTimeKind.Local).AddTicks(7810)
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2019, 6, 23, 19, 4, 24, 13, DateTimeKind.Local).AddTicks(7820),
                            Type = "Completa",
                            Updated = new DateTime(2019, 6, 23, 19, 4, 24, 13, DateTimeKind.Local).AddTicks(7820)
                        });
                });

            modelBuilder.Entity("Core.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<int>("ExamId");

                    b.Property<string>("Instruction")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("Sections");
                });

            modelBuilder.Entity("Core.Models.Question", b =>
                {
                    b.HasOne("Core.Models.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Models.Section", "Section")
                        .WithMany("Questions")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Models.Section", b =>
                {
                    b.HasOne("Core.Models.Exam", "Exam")
                        .WithMany("Sections")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
