// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

namespace Persistence.Migrations
{
    [DbContext(typeof(GeneratorDbContext))]
    [Migration("20190628225053_userExamRelationship")]
    partial class userExamRelationship
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Core.Models.ApplicationUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Core.Models.Exam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Subject");

                    b.Property<string>("Teacher");

                    b.Property<DateTime>("Updated");

                    b.Property<int>("UserId");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Exams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(1190),
                            Subject = "Historia",
                            Teacher = "Kakin",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(1210),
                            UserId = 0
                        });
                });

            modelBuilder.Entity("Core.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Answer");

                    b.Property<DateTime>("Created");

                    b.Property<string>("Options");

                    b.Property<int>("QuestionTypeId");

                    b.Property<int>("SectionId");

                    b.Property<string>("Title")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("QuestionTypeId");

                    b.HasIndex("SectionId");

                    b.ToTable("Questions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "true",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(6260),
                            QuestionTypeId = 1,
                            SectionId = 1,
                            Title = "Yo soy verdadero",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(6260)
                        },
                        new
                        {
                            Id = 2,
                            Answer = "true",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8190),
                            QuestionTypeId = 1,
                            SectionId = 1,
                            Title = "Yo soy verdadero",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8200)
                        },
                        new
                        {
                            Id = 3,
                            Answer = "true",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8220),
                            QuestionTypeId = 1,
                            SectionId = 1,
                            Title = "Yo soy verdadero",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8220)
                        },
                        new
                        {
                            Id = 4,
                            Answer = "true",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8220),
                            QuestionTypeId = 1,
                            SectionId = 1,
                            Title = "Yo soy verdadero",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8220)
                        },
                        new
                        {
                            Id = 5,
                            Answer = "false",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8230),
                            QuestionTypeId = 1,
                            SectionId = 1,
                            Title = "Yo soy falso",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8230)
                        },
                        new
                        {
                            Id = 6,
                            Answer = "false",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8230),
                            QuestionTypeId = 1,
                            SectionId = 1,
                            Title = "Yo soy falso",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8230)
                        },
                        new
                        {
                            Id = 7,
                            Answer = "false",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8230),
                            QuestionTypeId = 1,
                            SectionId = 1,
                            Title = "Yo soy falso",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8240)
                        },
                        new
                        {
                            Id = 8,
                            Answer = "true",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8240),
                            QuestionTypeId = 1,
                            SectionId = 1,
                            Title = "Yo soy verdadero",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8240)
                        },
                        new
                        {
                            Id = 9,
                            Answer = "false",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8240),
                            QuestionTypeId = 1,
                            SectionId = 1,
                            Title = "Yo soy falso",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8240)
                        },
                        new
                        {
                            Id = 10,
                            Answer = "true",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8250),
                            QuestionTypeId = 1,
                            SectionId = 1,
                            Title = "Yo soy verdadero",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8250)
                        },
                        new
                        {
                            Id = 11,
                            Answer = "true",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8250),
                            QuestionTypeId = 1,
                            SectionId = 1,
                            Title = "Yo soy verdadero",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8250)
                        },
                        new
                        {
                            Id = 12,
                            Answer = "true",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8250),
                            QuestionTypeId = 1,
                            SectionId = 1,
                            Title = "Yo soy verdadero",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8260)
                        },
                        new
                        {
                            Id = 13,
                            Answer = "false",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8260),
                            QuestionTypeId = 1,
                            SectionId = 1,
                            Title = "Yo soy falso",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8260)
                        },
                        new
                        {
                            Id = 14,
                            Answer = "false",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8260),
                            QuestionTypeId = 1,
                            SectionId = 1,
                            Title = "Yo soy falso",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8260)
                        },
                        new
                        {
                            Id = 15,
                            Answer = "a",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8270),
                            Options = "{a: \"Opcion a \", b: \"Opcion b \", c: \"Opcion c \", d: \"Opcion d \"}",
                            QuestionTypeId = 2,
                            SectionId = 2,
                            Title = "Que letra es la correcta",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8270)
                        },
                        new
                        {
                            Id = 16,
                            Answer = "a",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8750),
                            Options = "{a: \"Opcion a \", b: \"Opcion b \", c: \"Opcion c \", d: \"Opcion d \"}",
                            QuestionTypeId = 2,
                            SectionId = 2,
                            Title = "Que letra es la correcta",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8750)
                        },
                        new
                        {
                            Id = 17,
                            Answer = "d",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8770),
                            Options = "{a: \"Opcion a \", b: \"Opcion b \", c: \"Opcion c \", d: \"Opcion d \"}",
                            QuestionTypeId = 2,
                            SectionId = 2,
                            Title = "Que letra es la correcta",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8770)
                        },
                        new
                        {
                            Id = 18,
                            Answer = "a",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8770),
                            Options = "{a: \"Opcion a \", b: \"Opcion b \", c: \"Opcion c \", d: \"Opcion d \"}",
                            QuestionTypeId = 2,
                            SectionId = 2,
                            Title = "Que letra es la correcta",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8770)
                        },
                        new
                        {
                            Id = 19,
                            Answer = "b",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8780),
                            Options = "{a: \"Opcion a \", b: \"Opcion b \", c: \"Opcion c \", d: \"Opcion d \"}",
                            QuestionTypeId = 2,
                            SectionId = 2,
                            Title = "Que letra es la correcta",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8780)
                        },
                        new
                        {
                            Id = 20,
                            Answer = "c",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8780),
                            Options = "{a: \"Opcion a \", b: \"Opcion b \", c: \"Opcion c \", d: \"Opcion d \"}",
                            QuestionTypeId = 2,
                            SectionId = 2,
                            Title = "Que letra es la correcta",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8780)
                        },
                        new
                        {
                            Id = 21,
                            Answer = "d",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8790),
                            Options = "{a: \"Opcion a \", b: \"Opcion b \", c: \"Opcion c \", d: \"Opcion d \"}",
                            QuestionTypeId = 2,
                            SectionId = 2,
                            Title = "Que letra es la correcta",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8790)
                        },
                        new
                        {
                            Id = 22,
                            Answer = "a",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8790),
                            Options = "{a: \"Opcion a \", b: \"Opcion b \", c: \"Opcion c \", d: \"Opcion d \"}",
                            QuestionTypeId = 2,
                            SectionId = 2,
                            Title = "Que letra es la correcta",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8790)
                        },
                        new
                        {
                            Id = 23,
                            Answer = "b",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8790),
                            Options = "{a: \"Opcion a \", b: \"Opcion b \", c: \"Opcion c \", d: \"Opcion d \"}",
                            QuestionTypeId = 2,
                            SectionId = 2,
                            Title = "Que letra es la correcta",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8800)
                        },
                        new
                        {
                            Id = 24,
                            Answer = "a",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8800),
                            Options = "{a: \"Opcion a \", b: \"Opcion b \", c: \"Opcion c \", d: \"Opcion d \"}",
                            QuestionTypeId = 2,
                            SectionId = 2,
                            Title = "Que letra es la correcta",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8800)
                        },
                        new
                        {
                            Id = 25,
                            Answer = "a",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8800),
                            Options = "{a: \"Opcion a \", b: \"Opcion b \", c: \"Opcion c \", d: \"Opcion d \"}",
                            QuestionTypeId = 2,
                            SectionId = 2,
                            Title = "Que letra es la correcta",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8800)
                        },
                        new
                        {
                            Id = 26,
                            Answer = "a",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8810),
                            Options = "{a: \"Opcion a \", b: \"Opcion b \", c: \"Opcion c \", d: \"Opcion d \"}",
                            QuestionTypeId = 2,
                            SectionId = 2,
                            Title = "Que letra es la correcta",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8810)
                        },
                        new
                        {
                            Id = 27,
                            Answer = "d",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8810),
                            Options = "{a: \"Opcion a \", b: \"Opcion b \", c: \"Opcion c \", d: \"Opcion d \"}",
                            QuestionTypeId = 2,
                            SectionId = 2,
                            Title = "Que letra es la correcta",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8810)
                        },
                        new
                        {
                            Id = 28,
                            Answer = "c",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8810),
                            Options = "{a: \"Opcion a \", b: \"Opcion b \", c: \"Opcion c \", d: \"Opcion d \"}",
                            QuestionTypeId = 2,
                            SectionId = 2,
                            Title = "Que letra es la correcta",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8810)
                        },
                        new
                        {
                            Id = 29,
                            Answer = "b",
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8820),
                            Options = "{a: \"Opcion a \", b: \"Opcion b \", c: \"Opcion c \", d: \"Opcion d \"}",
                            QuestionTypeId = 2,
                            SectionId = 2,
                            Title = "Que letra es la correcta",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(8820)
                        });
                });

            modelBuilder.Entity("Core.Models.QuestionType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<string>("Type")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.ToTable("QuestionTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 431, DateTimeKind.Local).AddTicks(6800),
                            Type = "Verdadero o Falso",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 441, DateTimeKind.Local).AddTicks(6380)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 441, DateTimeKind.Local).AddTicks(8350),
                            Type = "Seleccion Multiple",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 441, DateTimeKind.Local).AddTicks(8350)
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 441, DateTimeKind.Local).AddTicks(8370),
                            Type = "Seleccion Simple",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 441, DateTimeKind.Local).AddTicks(8370)
                        },
                        new
                        {
                            Id = 4,
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 441, DateTimeKind.Local).AddTicks(8370),
                            Type = "Completa",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 441, DateTimeKind.Local).AddTicks(8370)
                        });
                });

            modelBuilder.Entity("Core.Models.Section", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Created");

                    b.Property<int>("ExamId");

                    b.Property<string>("Instruction")
                        .IsRequired();

                    b.Property<DateTime>("Updated");

                    b.HasKey("Id");

                    b.HasIndex("ExamId");

                    b.ToTable("Sections");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(3840),
                            ExamId = 1,
                            Instruction = "Escriba si es verdadero o falso",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(3850)
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(4900),
                            ExamId = 1,
                            Instruction = "Eliga la respuesta correcta",
                            Updated = new DateTime(2019, 6, 28, 18, 50, 52, 444, DateTimeKind.Local).AddTicks(4910)
                        });
                });

            modelBuilder.Entity("Core.Models.Exam", b =>
                {
                    b.HasOne("Core.Models.ApplicationUser", "User")
                        .WithMany("Exams")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Models.Question", b =>
                {
                    b.HasOne("Core.Models.QuestionType", "QuestionType")
                        .WithMany("Questions")
                        .HasForeignKey("QuestionTypeId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Core.Models.Section", "Section")
                        .WithMany("Questions")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("Core.Models.Section", b =>
                {
                    b.HasOne("Core.Models.Exam", "Exam")
                        .WithMany("Sections")
                        .HasForeignKey("ExamId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
